# Railway build configuration

# OPTION 1: Complex Railway-specific Dockerfile that forces Rust 1.77
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

# OPTION 2: Pre-built binary approach (uncomment to use)
# [build]
# builder = "DOCKERFILE"
# dockerfilePath = "Dockerfile.minimal"

# OPTION 3: Simplified build approach that might work better (uncomment to use)
# [build]
# builder = "DOCKERFILE"
# dockerfilePath = "Dockerfile.simple"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10